---
collections:
- name: community.general
  version: 9.0.1

roles:
- src: https://github.com/scheleaap/ansible-role-env-common.git
  version: master
  name: env-common-scheleaap
- src: https://github.com/scheleaap/ansible-role-env-desktop.git
  version: master
  name: env-desktop-scheleaap
- src: https://github.com/nickjj/ansible-docker.git
  version: "v2.4.0"
  name: docker
#- src: http://<host>/<user>/ansible-role-work/repository/archive.tar.gz?ref=master
#  name: work
